### ISSUE TITLE
cpp behavior file linking error

### ISSUE THREAD

**Issue by lyonthezhang** [ilpincy/argos3-kilobot#12]
I'm trying to write behavior files in cpp to be able to make use of our communication library that has classes. Everything compiles correctly, but upon trying to run this error appears:

```
dyld: lazy symbol binding failed: Symbol not found: ___kilobot_main
  Referenced from: /Users/lyonzhang/Desktop/argos stuff/argos3-kilobot-test-runs/build/examples/behaviors/make_cpp_work
  Expected in: flat namespace

dyld: Symbol not found: ___kilobot_main
  Referenced from: /Users/lyonzhang/Desktop/argos stuff/argos3-kilobot-test-runs/build/examples/behaviors/make_cpp_work
  Expected in: flat namespace
```

The only thing that's been modified is changing the file extension from .c to .cpp (and updating the corresponding name CMakeLists.txt). We've tried wrapping the #include <kilolib.h> with extern "C" but the exact same error occurs.

**Comment by ilpincy** [comment]
If you intend to use C++, I don't see the reason to stick to the C interface. The code you're making would not be portable to the real platforms anyway. The easiest way to work is to make a new kilobot controller by extending `CCI_Controller`, as shown in the [argos3-examples repository](https://github.com/ilpincy/argos3-examples).
