### ISSUE TITLE
argos3-kilobot not properly installed. [FATAL] Failed to initialize the space. [FATAL] Symbol "kilobot" not found

### ISSUE THREAD

**Issue by germanpatt** [ilpincy/argos3-kilobot#17]
hi there,
i have installed argos3_simulator-3.0.0-x86_64-beta59 in a xubuntu 18.4 distro. i installed argos3-kilobot following the readme instructions:

_mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ../src
make
sudo make install_

No errors where displayed during the installation. After that, i run _argos3 -q all_, but the kilobot entity is not shown...i get the following output:

**[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_media.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_spiri.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_footbot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_eyebot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_pointmass3d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_genericrobot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_prototype.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics3d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_entities.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics2d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_qtopengl.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_epuck.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3core_simulator.so"
AVAILABLE ACTUATORS
   [ differential_steering (default) ]
      The differential steering actuator.
   [ directional_leds (default) ]
      The directional LEDs actuator.
   [ footbot_distance_scanner (default) ]
      The foot-bot distance scanner actuator.
   [ footbot_gripper (default) ]
      The footbot gripper actuator.
   [ footbot_turret (default) ]
      The foot-bot turret actuator.
   [ gripper (default) ]
      The Gripper actuator.
   [ joints (default) ]
      The prototype joints actuator: controls a prototype entity's joints.
   [ leds (default) ]
      The LEDs actuator.
   [ magnets (default) ]
      The (electro)magnet actuator.
   [ quadrotor_position (default) ]
      The quadrotor position actuator.
   [ quadrotor_speed (default) ]
      The quadrotor speed actuator.
   [ radios (default) ]
      A generic radio actuator to send messages to nearby radios.
   [ range_and_bearing (default) ]
      The range and bearing actuator.
   [ tags (default) ]
      The tags actuator.
AVAILABLE SENSORS
   [ battery (default) ]
      A generic battery level sensor.
   [ cameras (default) ]
      A generic multi-camera sensor capable of running various algorithms
   [ colored_blob_omnidirectional_camera (rot_z_only) ]
      A generic omnidirectional camera sensor to detect colored blobs.
   [ colored_blob_perspective_camera (default) ]
      A generic perspective camera sensor to detect colored blobs.
   [ differential_steering (default) ]
      A generic differential steering sensor.
   [ epuck_proximity (default) ]
      The E-Puck proximity sensor.
   [ eyebot_light (rot_z_only) ]
      The eye-bot light sensor (optimized for 2D).
   [ eyebot_proximity (default) ]
      The eye-bot proximity sensor.
   [ footbot_base_ground (rot_z_only) ]
      The foot-bot base ground sensor.
   [ footbot_distance_scanner (rot_z_only) ]
      The foot-bot distance scanner sensor (optimized for 2D).
   [ footbot_light (rot_z_only) ]
      The foot-bot light sensor (optimized for 2D).
   [ footbot_motor_ground (rot_z_only) ]
      The foot-bot motor ground sensor.
   [ footbot_proximity (default) ]
      The foot-bot proximity sensor.
   [ footbot_turret_encoder (default) ]
      The foot-bot turret encoder sensor.
   [ ground (rot_z_only) ]
      A generic ground sensor (optimized for 2D).
   [ joints (default) ]
      The prototype joints sensor: monitors a prototype entity's joints.
   [ light (default) ]
      A generic light sensor.
   [ positioning (default) ]
      A generic positioning sensor.
   [ proximity (default) ]
      A generic proximity sensor.
   [ radios (default) ]
      A generic radio sensor to receive messages from nearby radios.
   [ range_and_bearing (medium) ]
      The range-and-bearing sensor.
AVAILABLE PHYSICS ENGINES
   [ dynamics2d ]
      A 2D dynamics physics engine.
   [ dynamics3d ]
      A 3D dynamics physics engine
   [ pointmass3d ]
      A 3D point-mass physics engine.
AVAILABLE MEDIA
   [ directional_led ]
      Manages directional LED entities.
   [ led ]
      Manages the LEDs.
   [ radio ]
      Enables communication between a radio actuator and radio sensor.
   [ range_and_bearing ]
      It simulates the communication across range-and-bearing-equipped robots.
   [ tag ]
      Manages tag entities.
AVAILABLE VISUALIZATIONS
   [ qt-opengl ]
      An interactive graphical renderer based on Qt and OpenGL.
AVAILABLE ENTITIES
   [ box ]
      A stretchable 3D box.
   [ cylinder ]
      A stretchable cylinder.
   [ e-puck ]
      The e-puck robot.
   [ eye-bot ]
      The eye-bot robot, developed in the Swarmanoid project.
   [ floor ]
      It contains the properties of the arena floor.
   [ foot-bot ]
      The foot-bot robot, developed in the Swarmanoid project.
   [ light ]
      A colored light.
   [ prototype ]
      A generic and configurable entity
   [ spiri ]
      The spiri robot, developed by Pleiades Robotics.**

then, if i want to run a kilbot example:

_argos3 -c src/examples/experiments/kilobot_blinky.argos_

i get:

**[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_media.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_spiri.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_footbot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_eyebot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_pointmass3d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_genericrobot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_prototype.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics3d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_entities.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics2d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_qtopengl.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_epuck.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3core_simulator.so"
[INFO] Not using threads
[INFO] Using random seed = 124
[INFO] Using simulation clock tick = 0.0322581
[INFO] Total experiment length in clock ticks = unlimited
[INFO] The physics engine "dyn2d" will perform 10 iterations per tick (dt = 0.00322581 sec)
[FATAL] Failed to initialize the space.
[FATAL] Symbol "kilobot" not found**

the examples argos3-examples work fine. We also tried in different computers (and different linux distros https://linuxmint.com/edition.php?id=269) and the problem is the same. do you have any idea what is going on?

thanks in advanced!

**Comment by germanpatt** [comment]
after runing _make_, there are some warnings...

**Scanning dependencies of target argos3plugin_simulator_kilolib_autogen
[  1%] Automatic MOC for target argos3plugin_simulator_kilolib
[  1%] Built target argos3plugin_simulator_kilolib_autogen
Scanning dependencies of target argos3plugin_simulator_kilolib
[  2%] Building C object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilolib.dir/control_interface/kilolib.c.o
/home/german/Documents/argos/argos3-kilobot/src/plugins/robots/kilobot/control_interface/kilolib.c: In function ‘main’:
/home/german/Documents/argos/argos3-kilobot/src/plugins/robots/kilobot/control_interface/kilolib.c:273:4: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
    ftruncate(kilo_state_fd, sizeof(kilobot_state_t));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  3%] Building C object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilolib.dir/control_interface/message_crc.c.o
[  4%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilolib.dir/argos3plugin_simulator_kilolib_autogen/mocs_compilation.cpp.o
[  5%] Linking CXX static library libargos3plugin_simulator_kilolib.a
[  5%] Built target argos3plugin_simulator_kilolib
Scanning dependencies of target argos3plugin_simulator_kilobot_autogen
[  6%] Automatic MOC for target argos3plugin_simulator_kilobot
[  6%] Built target argos3plugin_simulator_kilobot_autogen
Scanning dependencies of target argos3plugin_simulator_kilobot
[  8%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/control_interface/ci_kilobot_communication_actuator.cpp.o
[  9%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/control_interface/ci_kilobot_communication_sensor.cpp.o
[ 10%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/control_interface/ci_kilobot_controller.cpp.o
/home/german/Documents/argos/argos3-kilobot/src/plugins/robots/kilobot/control_interface/ci_kilobot_controller.cpp: In member function ‘virtual void CCI_KilobotController::Init(argos::TConfigurationNode&)’:
/home/german/Documents/argos/argos3-kilobot/src/plugins/robots/kilobot/control_interface/ci_kilobot_controller.cpp:59:18: warning: ignoring return value of ‘int ftruncate(int, __off_t)’, declared with attribute warn_unused_result [-Wunused-result]
       ::ftruncate(m_nSharedMemFD, sizeof(kilobot_state_t));
       ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 11%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/control_interface/ci_kilobot_led_actuator.cpp.o
[ 12%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/control_interface/ci_kilobot_light_sensor.cpp.o
[ 13%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/simulator/dynamics2d_kilobot_model.cpp.o
[ 14%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/simulator/pointmass3d_kilobot_model.cpp.o
[ 16%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/simulator/kilobot_entity.cpp.o
[ 17%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/simulator/kilobot_led_default_actuator.cpp.o
[ 18%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/simulator/kilobot_light_rotzonly_sensor.cpp.o
[ 19%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/simulator/kilobot_communication_default_actuator.cpp.o
[ 20%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/simulator/kilobot_communication_default_sensor.cpp.o
[ 21%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/simulator/kilobot_communication_entity.cpp.o
[ 22%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/simulator/kilobot_communication_medium.cpp.o
[ 24%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/simulator/qtopengl_kilobot.cpp.o
[ 25%] Building CXX object plugins/robots/kilobot/CMakeFiles/argos3plugin_simulator_kilobot.dir/argos3plugin_simulator_kilobot_autogen/mocs_compilation.cpp.o
[ 26%] Linking CXX shared library libargos3plugin_simulator_kilobot.so
[ 26%] Built target argos3plugin_simulator_kilobot
Scanning dependencies of target kilobot_diffusion_autogen
[ 27%] Automatic MOC for target kilobot_diffusion
[ 27%] Built target kilobot_diffusion_autogen
Scanning dependencies of target kilobot_diffusion
[ 28%] Building CXX object examples/controllers/kilobot_diffusion/CMakeFiles/kilobot_diffusion.dir/kilobot_diffusion.cpp.o
[ 29%] Building CXX object examples/controllers/kilobot_diffusion/CMakeFiles/kilobot_diffusion.dir/kilobot_diffusion_autogen/mocs_compilation.cpp.o
[ 31%] Linking CXX shared library libkilobot_diffusion.so
[ 31%] Built target kilobot_diffusion
Scanning dependencies of target kilobot_phototaxis_autogen
[ 32%] Automatic MOC for target kilobot_phototaxis
[ 32%] Built target kilobot_phototaxis_autogen
Scanning dependencies of target kilobot_phototaxis
[ 33%] Building CXX object examples/controllers/kilobot_phototaxis/CMakeFiles/kilobot_phototaxis.dir/kilobot_phototaxis.cpp.o
[ 34%] Building CXX object examples/controllers/kilobot_phototaxis/CMakeFiles/kilobot_phototaxis.dir/kilobot_phototaxis_autogen/mocs_compilation.cpp.o
[ 35%] Linking CXX shared library libkilobot_phototaxis.so
[ 35%] Built target kilobot_phototaxis
Scanning dependencies of target orbit_star_autogen
[ 36%] Automatic MOC for target orbit_star
[ 36%] Built target orbit_star_autogen
Scanning dependencies of target orbit_star
[ 37%] Building C object examples/behaviors/CMakeFiles/orbit_star.dir/orbit_star.c.o
[ 39%] Building CXX object examples/behaviors/CMakeFiles/orbit_star.dir/orbit_star_autogen/mocs_compilation.cpp.o
[ 40%] Linking CXX executable orbit_star
[ 40%] Built target orbit_star
Scanning dependencies of target test_speaker_mod_autogen
[ 41%] Automatic MOC for target test_speaker_mod
[ 41%] Built target test_speaker_mod_autogen
Scanning dependencies of target test_speaker_mod
[ 42%] Building C object examples/behaviors/CMakeFiles/test_speaker_mod.dir/test_speaker_mod.c.o
[ 43%] Building CXX object examples/behaviors/CMakeFiles/test_speaker_mod.dir/test_speaker_mod_autogen/mocs_compilation.cpp.o
[ 44%] Linking CXX executable test_speaker_mod
[ 44%] Built target test_speaker_mod
Scanning dependencies of target move_to_light_autogen
[ 45%] Automatic MOC for target move_to_light
[ 45%] Built target move_to_light_autogen
Scanning dependencies of target move_to_light
[ 47%] Building C object examples/behaviors/CMakeFiles/move_to_light.dir/move_to_light.c.o
[ 48%] Building CXX object examples/behaviors/CMakeFiles/move_to_light.dir/move_to_light_autogen/mocs_compilation.cpp.o
[ 49%] Linking CXX executable move_to_light
[ 49%] Built target move_to_light
Scanning dependencies of target simple_movement_autogen
[ 50%] Automatic MOC for target simple_movement
[ 50%] Built target simple_movement_autogen
Scanning dependencies of target simple_movement
[ 51%] Building C object examples/behaviors/CMakeFiles/simple_movement.dir/simple_movement.c.o
[ 52%] Building CXX object examples/behaviors/CMakeFiles/simple_movement.dir/simple_movement_autogen/mocs_compilation.cpp.o
[ 54%] Linking CXX executable simple_movement
[ 54%] Built target simple_movement
Scanning dependencies of target gradient_simple_autogen
[ 55%] Automatic MOC for target gradient_simple
[ 55%] Built target gradient_simple_autogen
Scanning dependencies of target gradient_simple
[ 56%] Building C object examples/behaviors/CMakeFiles/gradient_simple.dir/gradient_simple.c.o
[ 57%] Building CXX object examples/behaviors/CMakeFiles/gradient_simple.dir/gradient_simple_autogen/mocs_compilation.cpp.o
[ 58%] Linking CXX executable gradient_simple
[ 58%] Built target gradient_simple
Scanning dependencies of target test_listener_autogen
[ 59%] Automatic MOC for target test_listener
[ 59%] Built target test_listener_autogen
Scanning dependencies of target test_listener
[ 60%] Building C object examples/behaviors/CMakeFiles/test_listener.dir/test_listener.c.o
[ 62%] Building CXX object examples/behaviors/CMakeFiles/test_listener.dir/test_listener_autogen/mocs_compilation.cpp.o
[ 63%] Linking CXX executable test_listener
[ 63%] Built target test_listener
Scanning dependencies of target blinky_autogen
[ 64%] Automatic MOC for target blinky
[ 64%] Built target blinky_autogen
Scanning dependencies of target blinky
[ 65%] Building C object examples/behaviors/CMakeFiles/blinky.dir/blinky.c.o
[ 66%] Building CXX object examples/behaviors/CMakeFiles/blinky.dir/blinky_autogen/mocs_compilation.cpp.o
[ 67%] Linking CXX executable blinky
[ 67%] Built target blinky
Scanning dependencies of target test_speaker_autogen
[ 68%] Automatic MOC for target test_speaker
[ 68%] Built target test_speaker_autogen
Scanning dependencies of target test_speaker
[ 70%] Building C object examples/behaviors/CMakeFiles/test_speaker.dir/test_speaker.c.o
[ 71%] Building CXX object examples/behaviors/CMakeFiles/test_speaker.dir/test_speaker_autogen/mocs_compilation.cpp.o
[ 72%] Linking CXX executable test_speaker
[ 72%] Built target test_speaker
Scanning dependencies of target nonblocked_movement_autogen
[ 73%] Automatic MOC for target nonblocked_movement
[ 73%] Built target nonblocked_movement_autogen
Scanning dependencies of target nonblocked_movement
[ 74%] Building C object examples/behaviors/CMakeFiles/nonblocked_movement.dir/nonblocked_movement.c.o
[ 75%] Building CXX object examples/behaviors/CMakeFiles/nonblocked_movement.dir/nonblocked_movement_autogen/mocs_compilation.cpp.o
[ 77%] Linking CXX executable nonblocked_movement
[ 77%] Built target nonblocked_movement
Scanning dependencies of target test_listener_mod_autogen
[ 78%] Automatic MOC for target test_listener_mod
[ 78%] Built target test_listener_mod_autogen
Scanning dependencies of target test_listener_mod
[ 79%] Building C object examples/behaviors/CMakeFiles/test_listener_mod.dir/test_listener_mod.c.o
[ 80%] Building CXX object examples/behaviors/CMakeFiles/test_listener_mod.dir/test_listener_mod_autogen/mocs_compilation.cpp.o
[ 81%] Linking CXX executable test_listener_mod
[ 81%] Built target test_listener_mod
Scanning dependencies of target disperse_autogen
[ 82%] Automatic MOC for target disperse
[ 82%] Built target disperse_autogen
Scanning dependencies of target disperse
[ 83%] Building C object examples/behaviors/CMakeFiles/disperse.dir/disperse.c.o
[ 85%] Building CXX object examples/behaviors/CMakeFiles/disperse.dir/disperse_autogen/mocs_compilation.cpp.o
[ 86%] Linking CXX executable disperse
[ 86%] Built target disperse
Scanning dependencies of target orbit_planet_autogen
[ 87%] Automatic MOC for target orbit_planet
[ 87%] Built target orbit_planet_autogen
Scanning dependencies of target orbit_planet
[ 88%] Building C object examples/behaviors/CMakeFiles/orbit_planet.dir/orbit_planet.c.o
[ 89%] Building CXX object examples/behaviors/CMakeFiles/orbit_planet.dir/orbit_planet_autogen/mocs_compilation.cpp.o
[ 90%] Linking CXX executable orbit_planet
[ 90%] Built target orbit_planet
Scanning dependencies of target sync_autogen
[ 91%] Automatic MOC for target sync
[ 91%] Built target sync_autogen
Scanning dependencies of target sync
[ 93%] Building C object examples/behaviors/CMakeFiles/sync.dir/sync.c.o
[ 94%] Building CXX object examples/behaviors/CMakeFiles/sync.dir/sync_autogen/mocs_compilation.cpp.o
[ 95%] Linking CXX executable sync
[ 95%] Built target sync
Scanning dependencies of target test_debug_autogen
[ 96%] Automatic MOC for target test_debug
[ 96%] Built target test_debug_autogen
Scanning dependencies of target test_debug
[ 97%] Building C object examples/behaviors/CMakeFiles/test_debug.dir/test_debug.c.o
In file included from /home/german/Documents/argos/argos3-kilobot/src/examples/behaviors/test_debug.c:18:0:
/home/german/Documents/argos/argos3-kilobot/src/plugins/robots/kilobot/control_interface/debug.h: In function ‘debug_info_destroy’:
/home/german/Documents/argos/argos3-kilobot/src/plugins/robots/kilobot/control_interface/debug.h:29:4: warning: implicit declaration of function ‘asprintf’; did you mean ‘vsprintf’? [-Wimplicit-function-declaration]
    asprintf(&debug_info_fname, "/ARGoS_DEBUG_%ld_%s", (long)getppid(), kilo_str_id);
    ^~~~~~~~
    vsprintf
/home/german/Documents/argos/argos3-kilobot/src/plugins/robots/kilobot/control_interface/debug.h: In function ‘debug_info_create’:
/home/german/Documents/argos/argos3-kilobot/src/plugins/robots/kilobot/control_interface/debug.h:48:4: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
    ftruncate(debug_info_fd, sizeof(debug_info_t));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 98%] Building CXX object examples/behaviors/CMakeFiles/test_debug.dir/test_debug_autogen/mocs_compilation.cpp.o
[100%] Linking CXX executable test_debug
[100%] Built target test_debug**

the output of _sudo make install_ is as follows

**[  1%] Automatic MOC for target argos3plugin_simulator_kilolib
[  1%] Built target argos3plugin_simulator_kilolib_autogen
[  5%] Built target argos3plugin_simulator_kilolib
[  6%] Automatic MOC for target argos3plugin_simulator_kilobot
[  6%] Built target argos3plugin_simulator_kilobot_autogen
[ 26%] Built target argos3plugin_simulator_kilobot
[ 27%] Automatic MOC for target kilobot_diffusion
[ 27%] Built target kilobot_diffusion_autogen
[ 31%] Built target kilobot_diffusion
[ 32%] Automatic MOC for target kilobot_phototaxis
[ 32%] Built target kilobot_phototaxis_autogen
[ 35%] Built target kilobot_phototaxis
[ 36%] Automatic MOC for target orbit_star
[ 36%] Built target orbit_star_autogen
[ 40%] Built target orbit_star
[ 41%] Automatic MOC for target test_speaker_mod
[ 41%] Built target test_speaker_mod_autogen
[ 44%] Built target test_speaker_mod
[ 45%] Automatic MOC for target move_to_light
[ 45%] Built target move_to_light_autogen
[ 49%] Built target move_to_light
[ 50%] Automatic MOC for target simple_movement
[ 50%] Built target simple_movement_autogen
[ 54%] Built target simple_movement
[ 55%] Automatic MOC for target gradient_simple
[ 55%] Built target gradient_simple_autogen
[ 58%] Built target gradient_simple
[ 59%] Automatic MOC for target test_listener
[ 59%] Built target test_listener_autogen
[ 63%] Built target test_listener
[ 64%] Automatic MOC for target blinky
[ 64%] Built target blinky_autogen
[ 67%] Built target blinky
[ 68%] Automatic MOC for target test_speaker
[ 68%] Built target test_speaker_autogen
[ 72%] Built target test_speaker
[ 73%] Automatic MOC for target nonblocked_movement
[ 73%] Built target nonblocked_movement_autogen
[ 77%] Built target nonblocked_movement
[ 78%] Automatic MOC for target test_listener_mod
[ 78%] Built target test_listener_mod_autogen
[ 81%] Built target test_listener_mod
[ 82%] Automatic MOC for target disperse
[ 82%] Built target disperse_autogen
[ 86%] Built target disperse
[ 87%] Automatic MOC for target orbit_planet
[ 87%] Built target orbit_planet_autogen
[ 90%] Built target orbit_planet
[ 91%] Automatic MOC for target sync
[ 91%] Built target sync_autogen
[ 95%] Built target sync
[ 96%] Automatic MOC for target test_debug
[ 96%] Built target test_debug_autogen
[100%] Built target test_debug
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/control_interface/ci_kilobot_communication_actuator.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/control_interface/ci_kilobot_communication_sensor.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/control_interface/ci_kilobot_controller.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/control_interface/ci_kilobot_led_actuator.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/control_interface/ci_kilobot_light_sensor.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/control_interface/kilolib.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/control_interface/debug.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/control_interface/message.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/control_interface/message_crc.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/simulator/dynamics2d_kilobot_model.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/simulator/pointmass3d_kilobot_model.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/simulator/kilobot_entity.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/simulator/kilobot_measures.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/simulator/kilobot_led_default_actuator.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/simulator/kilobot_light_rotzonly_sensor.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/simulator/kilobot_communication_default_actuator.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/simulator/kilobot_communication_default_sensor.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/simulator/kilobot_communication_entity.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/simulator/kilobot_communication_medium.h
-- Installing: /usr/local/include/argos3/plugins/robots/kilobot/simulator/qtopengl_kilobot.h
-- Installing: /usr/local/lib/argos3/libargos3plugin_simulator_kilobot.so
-- Set runtime path of "/usr/local/lib/argos3/libargos3plugin_simulator_kilobot.so" to ""
-- Installing: /usr/local/lib/argos3/libargos3plugin_simulator_kilolib.a**

**Comment by ilpincy** [comment]
You have ARGoS installed in `/usr/lib/argos3`, but you installed the kilobot in `/usr/local/lib/argos3`.

You have two alternative solutions (don't do both):

1. Use the `ARGOS_PLUGIN_PATH` environment variable to tell ARGoS to look into `/usr/local/lib/argos3`:
```
export ARGOS_PLUGIN_PATH=/usr/local/lib/argos3
```

2. Recompile the kilobot code making sure that the target folder is `/usr` and not `/usr/local`:
```
cd argos3-kilobot
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr .
make
sudo make install
```

In case you go for the second solution, clean up `/usr/local` from all the `argos3` files.
