### ISSUE TITLE
Experiment Window Not Responsive to Mouse Click

### ISSUE THREAD

**Issue by sabrinalst** [ilpincy/argos3-kilobot#19]
Hi there,
I am running the example simulations. The window does pop up and I can change the value on the top bar via keyboard:
![image](https://github.com/user-attachments/assets/303ca8c3-dab2-480b-a396-2dea770c5b4d)
However, the other parts of the window are not responsive to any mouse click. 
```
[INFO] Loaded library "/usr/local/lib/argos3/libargos3plugin_simulator_kilobot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_eyebot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_drone.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics3d_magnetism.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_epuck.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics3d_floor.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_qtopengl.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics3d_gravity.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics3d_srocs.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_builderbot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_pipuck.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_genericrobot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3core_simulator.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_block.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_spiri.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_footbot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics2d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_entities.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_dynamics3d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_pointmass3d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_media.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_prototype.so"
[INFO] Not using threads
[INFO] Using random seed = 124
[INFO] Using simulation clock tick = 0.0322581
[INFO] Total experiment length in clock ticks = unlimited
[INFO] The physics engine "dyn2d" will perform 10 iterations per tick (dt = 0.00322581 sec)
NVD3D10: CPU cyclestats are disabled on client virtualization
NVD3D10: CPU cyclestats are disabled on client virtualization
```

Thank you for your support.

**Comment by ilpincy** [comment]
Hello @littleflashback, can you provide me with some detail?
1. Does the play button work at all? Or it's one of the buttons that is unresponsive?
2. Are you running ARGoS in a VM, and if so, which one?
3. What operating system are you using?
4. How did you install ARGoS – from the provided packages, or from the sources? (Looks like you used the packages, but I wanna make sure)

**Comment by sabrinalst** [comment]
1 None of the buttons are responsive.
2 & 3.  I am running ARGoS in WSL.
4. I installed ARGoS from the binary package.

**Comment by ilpincy** [comment]
OK – just to confirm, is WSL Windows Subsystem for Linux? If so, it's a use case I haven't thoroughly tested firsthand.

I see you're reporting this bug in the Kilobot repository. Is it because ARGoS works otherwise, and it stops working when the Kilobot plugin is installed?

**Comment by sabrinalst** [comment]
Yes, I am using Windows Subsystem for Linux. 
Just tried the standard ARGoS examples and they are having the same issue.

**Comment by ilpincy** [comment]
OK, so this issue should be in the main ARGoS repository, since it's not related to the kilobot plug-in.

I have never experienced this issue, but I'll see if I can find someone here that can reproduce it. Did you follow [these instructions](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps) to setup WSL?

The main question is whether this problem is specific to ARGoS or related to running QT applications in general.

**Comment by sabrinalst** [comment]
Hi there, since ARGoS was working when I first ran it, I tried reinstalling WSL and reproducing the issue. It seems to be a problem with VSCode WSL. Things worked fine before I opened any source code in VSCode WSL.

Thank you for your help!

**Comment by ilpincy** [comment]
OK, happy that it's resolved. Weird issue!
